-- Catalog foundations. Seed data follows in small, independently verifiable migrations.
create table public.product_types (id uuid primary key default gen_random_uuid(),code text not null unique check(length(btrim(code)) between 1 and 80),name text not null check(length(btrim(name)) between 1 and 200),quote_mode text not null default 'review' check(quote_mode in ('fixed','configurable','asset','package','review')),created_at timestamptz not null default now());
alter table public.products add column product_type_id uuid references public.product_types(id);
create index products_type_idx on public.products(product_type_id);
create table public.product_configuration_profiles (product_id uuid primary key references public.products(id) on delete cascade,product_kind text not null,source_category text,source_reference text,configuration_attribute_count integer check(configuration_attribute_count is null or configuration_attribute_count>=0),configuration_row_count integer check(configuration_row_count is null or configuration_row_count>=0),bom_count integer check(bom_count is null or bom_count>=0),review_note text,price_status text,historical_price_min numeric(16,0),historical_price_median numeric(16,0),historical_price_max numeric(16,0),last_sale_at timestamptz,source_file text not null,source_row integer,imported_at timestamptz not null default now(),check(historical_price_min is null or historical_price_min>0),check(historical_price_median is null or historical_price_median>0),check(historical_price_max is null or historical_price_max>0));
create table public.asset_locations (asset_id uuid primary key references public.inventory_assets(id) on delete cascade,zone text,address_text text not null,latitude numeric(9,6),longitude numeric(9,6),geolocation_status text not null default 'pending' check(geolocation_status in ('pending','verified','rejected')),source_state text,source_note text,source_reference text not null,check((latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180)),check((geolocation_status='verified') = (latitude is not null and longitude is not null)));
create index asset_locations_coordinates_idx on public.asset_locations(latitude,longitude) where geolocation_status='verified';
create table public.asset_price_observations (id uuid primary key default gen_random_uuid(),asset_id uuid not null references public.inventory_assets(id) on delete cascade,source_reference text not null,source_row integer,listed_amount_l numeric(16,0),listed_amount_v numeric(16,0),consistency text not null check(consistency in ('consistent','conflict','incomplete','missing')),currency text not null default 'COP' check(currency='COP'),commercial_unit text,observed_at date,imported_at timestamptz not null default now(),unique(asset_id,source_reference),check(listed_amount_l is null or listed_amount_l>0),check(listed_amount_v is null or listed_amount_v>0));
create index asset_price_observations_asset_idx on public.asset_price_observations(asset_id,imported_at desc);
do $$ declare t text; begin foreach t in array array['product_types','product_configuration_profiles','asset_locations','asset_price_observations'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from public,anon,authenticated',t); execute format('grant select on public.%I to authenticated',t); execute format('create policy staff_read on public.%I for select to authenticated using ((select private.has_permission(''cotizador.read'')))',t); end loop; end $$;
create function private.audit_product_profile_change() returns trigger language plpgsql set search_path='' as $$ begin insert into public.audit_events(actor_id,action,entity,entity_id) values((select auth.uid()),tg_op,tg_table_name,coalesce(to_jsonb(new)->>'product_id',to_jsonb(old)->>'product_id')); return coalesce(new,old); end; $$;
create function private.audit_asset_location_change() returns trigger language plpgsql set search_path='' as $$ begin insert into public.audit_events(actor_id,action,entity,entity_id) values((select auth.uid()),tg_op,tg_table_name,coalesce(to_jsonb(new)->>'asset_id',to_jsonb(old)->>'asset_id')); return coalesce(new,old); end; $$;
create trigger product_types_audit after insert or update or delete on public.product_types for each row execute function private.audit_identity_change();
create trigger asset_price_observations_audit after insert or update or delete on public.asset_price_observations for each row execute function private.audit_identity_change();
create trigger product_configuration_profiles_audit after insert or update or delete on public.product_configuration_profiles for each row execute function private.audit_product_profile_change();
create trigger asset_locations_audit after insert or update or delete on public.asset_locations for each row execute function private.audit_asset_location_change();
